name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ./.yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

      - name: Run TypeScript checks
        run: yarn run type-check

      - name: Run ESLint checks
        run: yarn run lint

      - name: Run commitlint checks (Push)
        run: npx commitlint --from ${{ github.event.before }} --to ${{ github.event.after }}
        if: github.event_name == 'push'

      - name: Build package
        run: yarn run build

      - name: Deploy apps to production
        run: yarn run release
        env:
          # GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          # GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          # GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
